### PR TITLE
Feature/can handle attachment

### PR DESCRIPTION
**Pull request by FarkasJanos**
## Checklist:
- [x] I've read the [Contributing page](https://github.com/junaidbhura/fly-dynamic-image-resizer/blob/master/CONTRIBUTING.md).
- [x] I've created an issue and referenced it here.
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

## Description
Added extra check to detect we got image attachment and we can resize and save that image

## How has this been tested?
Tested manually
Current modifications need higher WordPress version

- wp_get_attachment_image_url since 4.4.0
- wp_image_editor_supports since 3.5.0

## Types of changes
New feature (non-breaking change which adds functionality) #42

### CODE REVIEW

**Comment by FarkasJanos** [comment]
Maybe i can change the checks, to keep compatiblity with WordPress version 3.0.
What do you think?

**Comment by junaidbhura** [comment]
Thanks for the pull request @FarkasJanos ! Let me take a deeper look at this and get back to you!

**Comment by JDenne** [comment]
+1 on this. Thanks @FarkasJanos for your work on this. Look forward to it being merged. We're currently having to check if it's an SVG before using fly so this will be a big help.

**Comment by junaidbhura** [comment]
Hi @FarkasJanos apologies for the delayed response. I had the opportunity to look at this at length today. I've created another PR for this for the following reasons:

1. This plugin supports WordPress 3.0 and above, and it might break backwards compatibility
2. Performance reasons

Do you think you could pull this branch down and test if it fixes the issue? https://github.com/junaidbhura/fly-dynamic-image-resizer/pull/45

**Pull request closed without merging**
